# Generated by Django 5.0.6 on 2024-10-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gadget_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Laptop', 'Laptop'), ('Mobile', 'Mobile'), ('PC', 'PC'), ('Tablet', 'Tablet'), ('Camera', 'Camera'), ('Smartwatch', 'Smartwatch')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='static/img')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
