# Generated by Django 5.0.6 on 2024-10-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='userCreation',
            fields=[
                ('userName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
